# Site settings
title: tengyue
email: crystalyue0704@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  喜欢发呆的阿。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tengyue.me" # the base hostname & protocol for your site
twitter_username: divingteng
github_username:  divingteng
permalink: /:year/:month/:day/:title.html

# Build settings
markdown: kramdown
