# Site settings
title: tengyue
email: crystalyue0704@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  滕玥的博客。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tengyue.me" # the base hostname & protocol for your site
twitter_username:  divingteng
github_username:  divingteng
behance_username:  tengyue
permalink: /:year/:month/:day/:title.html
exclude: [node_modules]

# Build settings
markdown: kramdown
